apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespaces.yaml
- ./peerauth.yaml

helmCharts:
  - name: external-secrets
    releaseName: exsecrets-operator
    repo: https://charts.external-secrets.io
    version: 0.20.3
    namespace: exsecrets-operator

  - name: cloudnative-pg
    releaseName: cnpg-operator
    repo: https://cloudnative-pg.github.io/charts
    namespace: cnpg-operator

  - name: cert-manager
    releaseName: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: 1.21.1
    namespace: cert-manager
    valuesInline:
      crds:
        enabled: true

  - name: plugin-barman-cloud
    releaseName: plugin-barman-cloud
    repo: https://cloudnative-pg.github.io/charts
    namespace: cnpg-operator

  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istio-base
    version: 1.30.4 
    namespace: istio-system

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istiod
    namespace: istio-system
    version: 1.30.4 
    valuesInline:
      pilot:
        env:
          PILOT_ENABLE_AMBIENT: "true"

  - name: cni
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istio-cni
    namespace: istio-system
    version: 1.30.4 
    valuesInline:
      pilot:
        env:
          PILOT_ENABLE_AMBIENT: "true"

  - name: ztunnel
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: istio
    version: 1.30.4 
    namespace: istio-system
