apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-operator

---
apiVersion: v1
kind: Namespace
metadata:
  name: exsecrets-operator

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-identity
  namespace: exsecrets-operator
  annotations:
    azure.workload.identity/client-id: "33561d23-ed57-483b-b5e7-d82ca702e20b"
  labels:
    azure.workload.identity/use: "true"
