apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command:
          - sh
          - -c
          - |
            cat /etc/alertmanager/config.yaml | sed "s|DISCORD_WEBHOOK_URL|$(cat /secret/discord_webhook_url) |g" > /tmp/config/config.yaml 
        volumeMounts:
          - name: config-template
            mountPath: /etc/alertmanager/
          - name: config
            mountPath: /tmp/config
          - name: discord-webhook-url
            mountPath: /secret
      containers:
      - name: alertmanager
        image: prom/alertmanager
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9093
        args:
          - --config.file=/tmp/config/config.yaml
        volumeMounts:
          - name: config
            mountPath: /tmp/config
      volumes:
        - name: config-template
          configMap:
            name: alertmanager-config
        - name: config
          emptyDir: {}
        - name: discord-webhook-url
          secret:
            secretName: discord-webhook-url
