apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-config 
spec:
  #refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store

  target:
    name: alertmanager-config  #name of a secret in k8s
    creationPolicy: Owner #Owner, Merge, None
    #deletionPolicy: Retain, Delete
  #map secrets from azure keyvault to kubernetes secrets
  data:
    - secretKey: config.yaml # key name in k8s secret
      remoteRef:
        key: alertmanager-config
