# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  type: ClusterIP 
  ports:
  - name: alertmanager
    protocol: 
    port: 9093
    targetPort: 9093

