apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kuba-b-labs/homelab-with-argoCD
    targetRevision: HEAD
    path: infrastructure/operators
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
