apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgpass-pull
spec:
  #refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store

  target:
    name: postgresql-app  #name of a secret in k8s
    creationPolicy: Owner #Owner, Merge, None
    #deletionPolicy: Retain, Delete
  #map secrets from azure keyvault to kubernetes secrets
    template:
      engineVersion: v2
      data:
        pgpass: "{{ .pgpass }}" #| replace \"postgresql-rw\" \"postgresql-rw.postgres-db.svc.cluster.local\" }}
  data:
    - secretKey: pgpass # key name in k8s secret
      remoteRef:
        key: pgpass-postgres
