# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: 
  ports:
  - name: nginx
    protocol: TCP 
    port: 80
    targetPort: 80
  - name: nginx-metrics
    protocol: TCP
    port: 9113
    targetPort: 9100
