# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
        env:
          # Powiedz Grafanie, żeby szukała dashboardów w /var/lib/grafana/dashboards
         - name: GF_PATHS_PROVISIONING
           value: /etc/grafana/provisioning
        envFrom:
        - secretRef:
          name: grafana-credentials
        volumeMounts:
        - name: dashboard-test
          mountPath: /var/lib/grafana/dashboards
        - name: dashboard-provisioning
          mountPath: /etc/grafana/provisioning/dashboards
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
      restartPolicy: Always
      volumes:
        - name: dashboard-test
          configMap:
            name: basic-dashboard
        - name: dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: datasources
          configMap:
            name: data-sources

