apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: grafana
    spec:
      restartPolicy: Always
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            # Ścieżka, w której Grafana będzie szukać provisioning plików
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          envFrom:
            - secretRef:
                name: grafana-credentials
          volumeMounts:
            - name: dashboard-test
              mountPath: /var/lib/grafana/dashboards
            - name: dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: dashboard-test
          configMap:
            name: basic-dashboard
        - name: dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: datasources
          configMap:
            name: data-sources
