apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  # refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store

  target:
    name: grafana-credentials #name of a secret in k8s
    creationPolicy: Owner #Owner, Merge, None
    #deletionPolicy: Retain, Delete
  #map secrets from azure keyvault to kubernetes secrets
  dataFrom:
    - extract:
        key: grafana-credentials