apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - ./deployment.yaml
  - ./configmap-datasource.yaml
  - ./configmap-provisioning.yaml
  - ./namespace.yaml

configMapGenerator:
  - name: basic-dashboard
    files:
      - dashboards/basic.json 
  - name: default-dashboard
    files:
      - dashboards/default.json
