apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
- ./namespace.yaml


helmCharts:
  - name: loki
    releaseName: loki
    repo: https://grafana-community.github.io/helm-charts
    version: 18.11.2
    namespace: loki
    valuesFile: ./values_loki.yaml
  - name: alloy
    releaseName: alloy
    repo: https://grafana.github.io/helm-charts
    namespace: loki
    valuesFile: ./values_alloy.yaml


configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy=./config.alloy
    options:
      disableNameSuffixHash: true