apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 1m
    scrape_configs:
    - job_name: targets-based-on-file
      file_sd_configs: 
      - files:
        - /etc/prometheus/targets/*.json
        refresh_interval: 5m
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - alertmanager.alertmanager:9093
    rule_files:
      - /etc/prometheus/rules/*.yaml
