apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scrape-pods
  namespace: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  apiGroup: ""
roleRef:
  kind: Role
  name: prometheus-scraper
  apiGroup: rbac.authorization.k8s.io
