apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
  namespace: prometheus
spec:
  ports:
    - port: 9100
      targetPort: 9100
  clusterIP: None
  selector:
    app: node-exporter-daemonset
