apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      tenantId: "5ffaea82-3ab3-4fca-9159-a9af1fbdeff1"
      vaultUrl: "https://aks-dev-jb.vault.azure.net"
      authSecretRef:
        clientId:
          name: az-service-principal
          key: client_id
          namespace: argocd
        clientSecret:
          name: az-service-principal
          key: client_secret
          namespace: argocd
