apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      tenantId: "430f5e3e-ba39-4fae-bc6f-a8c41b3bd475"
      vaultUrl: "https://aks-dev-jb.vault.azure.net"
      # use workload identity
      authType: WorkloadIdentity
      serviceAccountRef:
        name: eso-sa
      # authSecretRef:
        # clientId:
        #   name: az-service-principal
        #   key: client_id
        #   namespace: argocd
        # clientSecret:
        #   name: az-service-principal
        #   key: client_secret
        #   namespace: argocd
