apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "5d91183a-6a85-4d43-8c9c-6be969c05c20"
  name: eso-identity
  labels:
    azure.workload.identity/use: "true"
