apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: barman-object-store
spec:
  configuration:
    azureCredentials:
      inheritFromAzureAD: true
    destinationPath: "https://cnpgbackupjb.blob.core.windows.net/backup"
    wal:
      compression: gzip