apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  labels:
    db: postgres
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  serviceAccountName: eso-identity
  # Persistent storage configuration
  storage:
    # storageClass: csi-hostpath-sc
    size: 1Gi
#  enableSuperuserAccess: true
#  superuserSecret:
#    name: cnpg-superuser
  bootstrap:
    initdb:
      database: linkding
      owner: app
#      secret:
#        name: postgresql-app1
#      database: app
#      owner: appuser

# # Replication
#   replica:
#     primary: postgresql
#     source: dr-example-cluster

# Backup properties
  backup:
    volumeSnapshot:
       className: csi-aws-vsc

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: "barman-object-store"

  inheritedMetadata:
    labels:
      azure.workload.identity/use: "true"
  # serviceAccountTemplate:
  #   metadata:
  #     annotations:
  #       azure.workload.identity/client-id: "77e24a32-9243-4d0e-b247-ea078cf3fd6d"
  #     labels:
  #       azure.workload.identity/use: "true"
